
-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Products Table
create table if not exists products (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  brand text,
  category text,
  sub_category text,
  condition text,
  price numeric,
  image text,
  description text,
  detailed_description jsonb,
  specs jsonb,
  rating numeric,
  stock integer,
  discount_price numeric,
  is_on_sale boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Orders Table
create table if not exists orders (
  id uuid default uuid_generate_v4() primary key,
  customer_name text,
  email text,
  address text,
  phone text,
  total numeric,
  status text default 'pending',
  payment_method text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Order Items Table
create table if not exists order_items (
  id uuid default uuid_generate_v4() primary key,
  order_id uuid references orders(id) on delete cascade,
  product_id uuid references products(id),
  product_name text,
  quantity integer,
  price numeric
);

-- Admin Users
create table if not exists admins (
  id uuid references auth.users not null primary key,
  email text
);

-- Blogs Table
create table if not exists blogs (
  id uuid default uuid_generate_v4() primary key,
  title text not null,
  excerpt text,
  content text,
  image text,
  category text,
  author text default 'App Admin',
  read_time text,
  views integer default 0,
  tags text[],
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Guides Table
create table if not exists guides (
  id uuid default uuid_generate_v4() primary key,
  title text not null,
  category text,
  description text,
  content text,
  read_time text,
  image text,
  video_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Pages Table (for About, Terms, etc.)
create table if not exists pages (
  id uuid default uuid_generate_v4() primary key,
  slug text unique not null,
  title text not null,
  content jsonb, 
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Banners/Slides Table
create table if not exists banners (
  id uuid default uuid_generate_v4() primary key,
  title text,
  description text,
  image_url text not null,
  link_url text, 
  display_order integer default 0,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Activity Logs for Real-time Dashboard
CREATE TABLE activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    action TEXT NOT NULL, -- 'view_page', 'add_to_cart', 'search', etc.
    details TEXT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Allow public insert for anonymous tracking (demo purpose)
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert" ON activity_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow admin select" ON activity_logs FOR SELECT USING (true); -- Ideally restrict to admin
